package com.kkh.algo.codility.naver

import java.util.*

fun main(){
    println(solution("MSSLS"))
    println(solution("LLMS"))
    println(solution("SMS"))
    println(solution("SMLSMLSMLSSMLSMLSMLSSMLSMLSMLSSMLSMLSMLSSMLSMLSMLSSMLSMLSMLSSMLSMLSMLSSMLSMLSMLSSMLSMLSMLSSMLSMLSMLSSMLSMLSMLSSMLSMLSMLSSMLSMLSMLSSMLSMLSMLSSMLSMLSMLSSMLSMLSMLSSMLSMLSMLSSMLSMLSMLSSMLSMLSMLSSMLSMLSMLSSMLSMLSMLSSMLSMLSMLSSMLSMLSMLSSMLSMLSMLSSMLSMLSMLSSMLSMLSMLSSMLSMLSMLSSMLSMLSMLSSMLSMLSMLSSMLSMLSMLSSMLSMLSMLSSMLSMLSMLSSMLSMLSMLSSMLSMLSMLSSMLSMLSMLSSMLSMLSMLSSMLSMLSMLSSMLSMLSMLSSMLSMLSMLSSMLSMLSMLSSMLSMLSMLSSMLSMLSMLSSMLSMLSMLSSMLSMLSMLSSMLSMLSMLSSMLSMLSMLSSMLSMLSMLSSMLSMLSMLSSMLSMLSMLSSMLSMLSMLSSMLSMLSMLSSMLSMLSMLSSMLSMLSMLSSMLSMLSMLSSMLSMLSMLSSMLSMLSMLSSMLSMLSMLSSMLSMLSMLSSMLSMLSMLSSMLSMLSMLSSMLSMLSMLSSMLSMLSMLSSMLSMLSMLSSMLSMLSMLSSMLSMLSMLSSMLSMLSMLSSMLSMLSMLSSMLSMLSMLSSMLSMLSMLSSMLSMLSMLSSMLSMLSMLSSMLSMLSMLSSMLSMLSMLSSMLSMLSMLSSMLSMLSMLSSMLSMLSMLSSMLSMLSMLSSMLSMLSMLSSMLSMLSMLSSMLSMLSMLSSMLSMLSMLSSMLSMLSMLSSMLSMLSMLSSMLSMLSMLSSMLSMLSMLSSMLSMLSMLSSMLSMLSMLSSMLSMLSMLSSMLSMLSMLSSMLSMLSMLSSMLSMLSMLSSMLSMLSMLSSMLSMLSMLSSMLSMLSMLSSMLSMLSMLSSMLSMLSMLSSMLSMLSMLSSMLSMLSMLSSMLSMLSMLSSMLSMLSMLS"))
}

fun solution(T:String):String{
    val arr = T.toCharArray()
    Arrays.sort(arr)
    val sb = StringBuilder()
    for(c in arr){
        sb.append(c)
    }
    return sb.reverse().toString()
}